version: "3.9"
services:
  database:
    image: postgres        
    restart: unless-stopped
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
volumes:
  database-data:
